Preparing Makefiles

diff --git a/ex02/Makefile b/ex02/Makefile
--- a/ex02/Makefile
+++ b/ex02/Makefile
@@ -15,42 +15,105 @@ SRC			=	$(addprefix $(SRC_DIR), $(addsuffix .cpp, $(SRC_FIL)))
 OBJ			=	$(addprefix $(BUI_DIR), $(addsuffix .o, $(SRC_FIL)))
 OBJF		=	.cache_exists
 
+# === Terminal Colors ===
+NO_COLOR		:=	\033[m
+ERROR_COLOR		:=	\033[0;31m
+OK_COLOR		:=	\033[0;32m
+LIN_COLOR		:=	\033[0;33m
+COM_COLOR		:=	\033[0;34m
+EXE_COLOR		:=	\033[0;35m
+OBJ_COLOR		:=	\033[0;36m
+WARN_COLOR		:=	\033[0;33m
+
+# === Output Strings ===
+OK_STRING		:=	[OK]
+ERROR_STRING	:=	[ERROR]
+WARN_STRING		:=	[WARNING]
+COM_STRING		:=	Compiling
+LIN_STRING		:=	Linking
+
+# === Targets ===
+
+.PHONY: all clean fclean re debug sanitize tags .clangd
+
 all: $(NAME)
 
+define link_and_test
+printf "%b" "$(LIN_COLOR)$(LIN_STRING) $(EXE_COLOR)$(@F)$(NO_COLOR)\r"; \
+$(1) 2> $@.log; \
+RESULT=$$?; \
+if [ $$RESULT -ne 0 ]; then \
+  printf "%-60b%b" "$(LIN_COLOR)$(LIN_STRING)$(EXE_COLOR) $@" "$(ERROR_COLOR)$(ERROR_STRING)$(NO_COLOR)\n"   ; \
+elif [ -s $@.log ]; then \
+  printf "%-60b%b" "$(LIN_COLOR)$(LIN_STRING)$(EXE_COLOR) $@" "$(WARN_COLOR)$(WARN_STRING)$(NO_COLOR)\n"   ; \
+else  \
+  printf "%-60b%b" "$(LIN_COLOR)$(LIN_STRING)$(EXE_COLOR) $(@F)" "$(OK_COLOR)$(OK_STRING)$(NO_COLOR)\n"   ; \
+fi; \
+cat $@.log; \
+rm -f $@.log; \
+exit $$RESULT
+endef
+
 $(NAME): $(OBJ)
-	@echo "Linking $@..."
-	@$(CXX) $(OBJ) -o $@
-	@echo "$@ executable is ready! :D"
+	@$(call link_and_test,$(CXX) $(LDFLAGS) $^ -o $@ $(LDLIBS))
 
-$(BUI_DIR)%.o: $(SRC_DIR)%.cpp | $(OBJF)
-	@mkdir -p $(dir $@)
-	@echo "Compiling $<..."
-	@$(CXX) $(CXXFLAGS) -c $< -o $@
+define compile_and_test
+printf "%b" "$(COM_COLOR)$(COM_STRING) $(OBJ_COLOR)$(@F)$(NO_COLOR)\r"; \
+$(1) 2> $@.log; \
+RESULT=$$?; \
+if [ $$RESULT -ne 0 ]; then \
+  printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(ERROR_COLOR)$(ERROR_STRING)$(NO_COLOR)\n"   ; \
+elif [ -s $@.log ]; then \
+  printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $@" "$(WARN_COLOR)$(WARN_STRING)$(NO_COLOR)\n"   ; \
+else  \
+  printf "%-60b%b" "$(COM_COLOR)$(COM_STRING)$(OBJ_COLOR) $(@F)" "$(OK_COLOR)$(OK_STRING)$(NO_COLOR)\n"   ; \
+fi; \
+cat $@.log; \
+rm -f $@.log; \
+exit $$RESULT
+endef
 
-$(OBJF):
-	@touch $(OBJF)
+$(BUI_DIR)%.o: $(SRC_DIR)%.cpp | $(BUI_DIR)
+	@mkdir -p $(@D)
+	@$(call compile_and_test,$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@)
 
-.clangd: Makefile
-	@echo "Making clangd configuration file"
-	@echo -n																\
-	"CompileFlags:\n"														\
-	"  Compiler: clang\n"													\
-	"  Add:\n"																\
-	"    - \"-Wall -Wextra -Werror\"\n"										\
-	"    - \""$(42_FLAGS)"\"\n"	> .clangd
-	@for file in $(INC_DIR); do												\
-		echo "     - \"-I"$(shell pwd)"/"$$file"\"" >> .clangd;				\
-	done ;
-	@echo $(GREEN) "Done" $(RESET)
+$(BUI_DIR):
+	@mkdir -p $@
 
 clean:
-	@echo "Removing build files..."
-	@rm -rf $(BUI_DIR) $(OBJF)
+	@rm -rf $(BUI_DIR)
 
 fclean: clean
-	@echo "Removing $(NAME)..."
-	@rm -rf $(NAME)
+	@rm -f $(NAME)
 
 re: fclean all
 
-.PHONY: all clean fclean re
+.clangd: Makefile
+	@echo "Generating .clangd config"
+	@echo "CompileFlags:" > .clangd
+	@echo "  Add:" >> .clangd
+	@for flag in $(CXXFLAGS); do \
+		echo "    - '$$flag'" >> .clangd; \
+	done
+	@for flag in $(CPPFLAGS); do \
+		echo "    - '$$flag'" >> .clangd; \
+	done
+	@for dir in $(INC_DIR); do \
+		abs_dir=$$(realpath $$dir) ; \
+		echo "    - '-I$$abs_dir'" >> .clangd ; \
+	done
+	@echo "$(OK_COLOR)[.clangd generated]$(NO_COLOR)"
+
+tags:
+	@echo "Generating tags..."
+	ctags -R --languages=C++ --c++-kinds=+cfpsv --fields=+iaS --extras=+q $(SRC_DIR) $(INC_DIR)
+	@echo "$(OK_COLOR)[tags file generated]$(NO_COLOR)"
+
+debug:
+	@$(MAKE) MODE=debug
+
+sanitize:
+	@$(MAKE) MODE=sanitize
+
+# === Dependency Include ===
+-include $(DEP)
